# Generated by Django 5.2 on 2025-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='Загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название фильма')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('genre', models.CharField(choices=[('Боевик', 'Боевик'), ('Приключения', 'Приключения'), ('Комедия', 'Комедия'), ('Драма', 'Драма'), ('Фэнтези', 'Фэнтези'), ('Ужасы', 'Ужасы'), ('Мистика', 'Мистика'), ('Романтика', 'Романтика'), ('Фантастика', 'Фантастика'), ('Триллер', 'Триллер'), ('Документальный', 'Документальный'), ('Биография', 'Биография'), ('Криминал', 'Криминал'), ('Исторический', 'Исторический'), ('Военный', 'Военный'), ('Спорт', 'Спорт'), ('Психологический', 'Психологический')], default='Фантастика', max_length=100, verbose_name='Укажите жанр')),
                ('author', models.CharField(default='Неизвестен', max_length=100, verbose_name='Режиссёр')),
                ('description', models.TextField(verbose_name='Укажите описание фильма')),
                ('audio_book', models.URLField(verbose_name='Ссылка на трейлер фильма')),
                ('page_number', models.PositiveIntegerField(default=90, null=True, verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
