# Generated by Django 5.2 on 2025-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_films_delete_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='audio_book',
        ),
        migrations.RemoveField(
            model_name='films',
            name='author',
        ),
        migrations.RemoveField(
            model_name='films',
            name='page_number',
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.CharField(default='Неизвестен', max_length=100, verbose_name='Режиссёр'),
        ),
        migrations.AddField(
            model_name='films',
            name='duration',
            field=models.PositiveIntegerField(default=90, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='films',
            name='trailer_url',
            field=models.URLField(default='https://example.com', verbose_name='Ссылка на трейлер фильма'),
        ),
    ]
