# Generated by Django 5.2 on 2025-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_films_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='create_at',
            field=models.DateTimeField(verbose_name='Дата выхода'),
        ),
    ]
