# Generated by Django 5.2 on 2025-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_films_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='create_at',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
