# Generated by Django 5.2 on 2025-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
