# Generated by Django 5.2 on 2025-05-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parser_Zetflix',
            new_name='Parser_Imdb',
        ),
    ]
