# Generated by Django 5.2 on 2025-05-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_parser_zetflix_parser_imdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parser_Imdb',
            new_name='Parser_Kinob',
        ),
    ]
